spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformTransactionManager
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: AssetManagement
server:
  port: 8080